### ISSUE TITLE
stream_data() should check for rows before call to insert_data()

### ISSUE THREAD

**Issue by devonlazarus** [Sonos-DataScience/CJ-Upload-service#4]
It appears it is possible there are no rows for a given day returned from the CJ Affiliate API. In the current implementation, this will raise an exception:
```
400 POST https://www.googleapis.com/bigquery/v2/projects/sonos-141919/datasets/8271193/tables/cj_publisher_test/insertAll: No rows present in the request.: BadRequest
Traceback (most recent call last):
File "/var/task/cj_upload_service.py", line 153, in handler
process_cj_data()
File "/var/task/cj_upload_service.py", line 150, in process_cj_data
stream_data("8271193", os.environ['CJ_PUBLISHER_TABLE'], upload_bq_publisher_rows, bigquery_client)
File "/var/task/cj_upload_service.py", line 54, in stream_data
errors = table.insert_data(load_data)
File "/var/task/google/cloud/bigquery/table.py", line 816, in insert_data
data=data)
File "/var/task/google/cloud/_http.py", line 293, in api_request
raise exceptions.from_http_response(response)
google.cloud.exceptions.BadRequest: 400 POST https://www.googleapis.com/bigquery/v2/projects/sonos-141919/datasets/8271193/tables/cj_publisher_test/insertAll: No rows present in the request.
```

Bug:
    unhandled exception when insert has no rows
Expected behavior:
    No exception is raised and log message indicated no rows were inserted

**Comment by jahilliard** [comment]
Well this is certainly an edge case we should take into account.  Let me work on a fix.

**Comment by jahilliard** [comment]
fix pushed to master
